name: van_detector
version: 1.0.0+1
description: A Flutter app for detecting white delivery vans

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+8
  tflite: ^1.1.2
  permission_handler: ^11.0.1
  provider: ^6.1.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  flutter_sound: ^10.0.1
  path_provider_android: ^2.1.1
  path_provider_ios: ^2.1.1
  path_provider_linux: ^2.1.1
  path_provider_macos: ^2.1.1
  path_provider_windows: ^2.1.1
  video_player: ^2.8.1
  object_detector: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/
    - assets/images/
    - assets/sounds/
